# Versi file compose
version: '3.8'

# Di sinilah kita mendefinisikan semua "layanan" (container)
services:

  # Layanan 1: Database (Kita pakai MariaDB sesuai setup kamu)
  database:
    image: mariadb:10.11 # Kamu bisa ganti versi
    container_name: proyek-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nyomet2304
      MYSQL_DATABASE: db_proyek_kolaborasi
    volumes:
      - db-data:/var/lib/mysql # Simpan data database di volume
    networks:
      - app-network

  # Layanan 2: Web Server (Apache + PHP)
  web:
    image: webdevops/php-apache:8.2 # Ganti dari 'build: .' jadi 'image:'
    container_name: proyek-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/app:z # Folder di container sekarang /app (bukan /var/www/html)
    environment:
      - WEB_DOCUMENT_ROOT=/app/public # <-- INI KUNCI BUAT LARAVEL
    depends_on:
      - database
    networks:
      - app-network

# Jaringan internal biar 'web' dan 'database' bisa ngobrol
networks:
  app-network:
    driver: bridge

# Volume untuk nyimpen data database secara permanen
volumes:
  db-data:
    driver: local
