# Versi file compose
version: '3.8'

# Di sinilah kita mendefinisikan semua "layanan" (container)
services:

  # Layanan 1: Database (Kita pakai MariaDB sesuai setup kamu)
  database:
    image: mariadb:10.11 # Kamu bisa ganti versi
    container_name: proyek-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nyomet2304
      MYSQL_DATABASE: db_proyek_kolaborasi
    volumes:
      - db-data:/var/lib/mysql # Simpan data database di volume
    networks:
      - app-network

  # Layanan 2: Web Server (Apache + PHP)
  web:
    build: . # "Build" container ini dari Dockerfile di folder ini
    container_name: proyek-web
    restart: unless-stopped
    ports:
      - "8080:80" # Map port 8080 host ke 80 container
    volumes:
      - ./src:/var/www/html:z # Sambungin folder src kita ke folder web Apache
    depends_on:
      - database # Bilang ke Docker: "Nyalain database DULU, baru nyalain web"
    networks:
      - app-network

# Jaringan internal biar 'web' dan 'database' bisa ngobrol
networks:
  app-network:
    driver: bridge

# Volume untuk nyimpen data database secara permanen
volumes:
  db-data:
    driver: local
